# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - SnapNFix

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./app-publish

      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Create deployment package
        run: |
          cd ./app-publish
          zip -r ../deploy.zip ./*
          cd ..
          echo "Created deployment package:"
          ls -la deploy.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_06BA40B678CF4D45AAD3516C5145E5D1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1E720880C2914ADC95DCAB506BD89790 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5E30D59A90144B76B2421967B6DA2A79 }}

      - name: Get resource group name
        id: get-resource-group
        uses: azure/cli@v1
        with:
          inlineScript: |
            RESOURCE_GROUP=$(az webapp list --query "[?name=='SnapNFix-Backend'].resourceGroup" -o tsv)
            echo "Resource group found: $RESOURCE_GROUP"
            echo "RESOURCE_GROUP=$RESOURCE_GROUP" >> $GITHUB_ENV

      - name: Stop Web App before deployment
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp stop --name "SnapNFix-Backend" --resource-group "${{ env.RESOURCE_GROUP }}"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "SnapNFix-Backend"
          slot-name: "Production"
          package: ./deploy.zip

      - name: Start Web App after deployment
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp start --name "SnapNFix-Backend" --resource-group "${{ env.RESOURCE_GROUP }}"
